// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-6_CjgrE96qbmvwD6JhFcrL6guWF-r8',
    appId: '1:336028448863:android:5eff562581632fe62c43ea',
    messagingSenderId: '336028448863',
    projectId: 'ecoapp-1b718',
    databaseURL: 'https://ecoapp-1b718-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecoapp-1b718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-eORfw7GcXzcYZ576VAyrA10-Mp-3pJM',
    appId: '1:336028448863:ios:3aff354f37ee680d2c43ea',
    messagingSenderId: '336028448863',
    projectId: 'ecoapp-1b718',
    databaseURL: 'https://ecoapp-1b718-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecoapp-1b718.appspot.com',
    androidClientId: '336028448863-77ecdki8ca6q43o2kfhlbugdb8j58i3b.apps.googleusercontent.com',
    iosClientId: '336028448863-ph36g8bjolv9ntcqlq8ta2ev8g0bge1b.apps.googleusercontent.com',
    iosBundleId: 'com.ecoapp.ecoAppProject',
  );
}
